spring:
  name: books-test-task
  main:
    banner-mode: 'off'
    log-startup-info: false
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    password: 123
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    default-schema: public
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.json

server:
  servlet:
    context-path: /api
  port: '8080'

#hibernate:
#  show_sql: true
#  format_sql: true
#  highlight_sql: true


